version: '3'

services:
  
  db:
    image: mysql:8.0
    container_name: mysqldb3
    env_file: ./docker/db/mysqldb.env
    environment:
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
    - ./docker/db/data:/var/lib/mysql
    - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
    - ./docker/db/sql:/docker-entrypoint-initdb.d
    ports:
    - 3306:3306
    
  app:
    build: .
    container_name: nodeapp
    env_file: ./myapp/app.env
    environment:
      - TZ=Asia/Tokyo
      - DEBUG=app:*
    tty: true
    ports:
      - '3000:3000'
    volumes:
      - ./myapp:/app
    depends_on: 
      - db