const dateClass = require('./controllers/class/dataFormat');
const format = new dateClass();
require('date-utils');
const now = new Date();
let date = now.toFormat('YYMMDDHH24MI');
let f = '2020-11-26 12:00';
let res = new dateClass().formatDateToInt(f);
let current = new dateClass().current;
let result = new dateClass().formatDateToString(date);
let rest = date.match(/.{2}/g);
var date1 = new Date(2020, 1, 1);
var date2 = new Date(2020, 2, 5);
var termDay = (date2 - date1) / 86400000;
const date3 = '2020-12-04 12:20';
const a = format.checkLimitDate(date3);
console.log(date3);
console.log(a);